version: "3.8"

services:
   node:
        env_file:
            - .env 
        build: . 
        command: npm start
        ports:
            - "162.214.104.227:80:80"
        volumes: 
            - .:/$HOME/akiosdev/app
