version: "3.8"

services:
    app:
        env_file:
            - .env 
        build: . 
        command: npm start
        ports:
            - "8080:8080"
        volumes: 
            - .:/$HOME/akiosdev/app
